### ISSUE TITLE
Add a workflow setting to include/download headers

### ISSUE THREAD

**Issue by AFCMS** [mrcjkb/lua-typecheck-action#3]
Sumneko's language server support configuring directories for external headers with the `workspace.library` setting.

https://github.com/sumneko/lua-language-server/wiki/Configuration-File

But we can't really add these headers directly to the repo so we can't use this setting.

The solution would be to add a setting to the workflow that allows including headers from external git repository.

**Comment by mrcjkb** [comment]
I will leave this issue open for the LuaRocks support.

For external GitHub repositories, you can use the [`checkout`](https://github.com/actions/checkout) action:

```yaml
- name: Checkout dependency xyz
  uses: actions/checkout@v3
  with:
    repository: "owner/xyz"
    path: "deps/xyz"
```

and then you can add `"deps/xyz"` to the `workspace.library` setting.
