### ISSUE TITLE
Example for nix setup with neodev.

### ISSUE THREAD

**Issue by pysan3** [mrcjkb/lua-typecheck-action#34]
Hi, I came across this action and I'm currently trying to integrate it into my plugin.
Being able to do type check before all commits would be amazing!

However, all files are raising errors since they cannot find the `vim` global variable at the moment.

When I look at your [`haskell-tools.nvim`](https://github.com/mrcjkb/haskell-tools.nvim), you are doing some nix magic to install neodev and other plugins.

I don't have any experience with nix or nixos, so I'd be glad if you could give me an example of how to setup neovim with neodev installed to use this action.

Thanks in advance!

**Comment by mrcjkb** [comment]
Hey :wave: 

There are two ways you can solve the `vim` global issue with this action:

-  Add a [.luarc.json](https://github.com/LuaLS/lua-language-server/wiki/Configuration-File#luarcjson) with the setting[^1]:
  
[^1]: see the [JSON schema](https://github.com/LuaLS/vscode-lua/blob/f7ce0e6429ea2238c57450bbe7cb8ee770c1753a/setting/schema.json#L359C24-L359C24).

```json
{
  "Lua.diagnostics.globals": ["vim"]
}
```

or

- see [this comment](https://github.com/mrcjkb/lua-typecheck-action/issues/3#issuecomment-1418273692) on how to checkout neodev. You could potentially also use luarocks to install dependencies, but I don't think neodev is on luarocks as of today.

**Comment by pysan3** [comment]
Thanks for you quick response!

1 is a no-go for me since I wanted to check if I'm calling the vim apis correctly as well.

I managed to set it up so I'd like to share here for others.

- I had to create a dedicated `.luarc.json` file for the action since it needs hardcoded paths. So I placed it into `.github/workflows/.luarc.json` and mention that with the action argument.

```json
// ./.github/workflows/.luarc.json
{
  "$schema": "https://raw.githubusercontent.com/sumneko/vscode-lua/master/setting/schema.json",
  "runtime.version": "LuaJIT",
  "runtime.path": [
    "lua/?.lua",
    "lua/?/init.lua"
  ],
  "workspace.library": [
    "/github/workspace/deps/neodev.nvim/types/stable"
  ],
  "diagnostics.libraryFiles": "Disable",
  "workspace.checkThirdParty": "Disable"
}
```

```yaml
# ./.github/workflows/lua_ls-typecheck.yml
# you could add `tests` folder at the end but it will raise errors for `describe, it, ...` anyways...
name: lua_ls-typecheck
on:
  pull_request: ~
  push:
    branches:
      - '*'

jobs:
  build:
    name: Type Check Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Checkout dependency neodev
        uses: actions/checkout@v3
        with:
          repository: "folke/neodev.nvim"
          path: "deps/neodev.nvim"

      - name: Type Check Code Base
        uses: mrcjkb/lua-typecheck-action@v0.1.2
        with:
          configpath: .github/workflows/.luarc.json
          directories: |
            lua
```
